services:
  api:
    container_name: flemot-api
    build:
      context: ./backend
    
    ports:
      - "8002:8080"


    # depends_on:
    #   - mongo

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - MongoDbSettings__ConnectionString=${MONGO_CONNECTION_STRING}
      - MongoDbSettings__DatabaseName=${MONGO_DATABASE_NAME}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    
    restart: always