version: '3.8'

services:
  # Ce service est la base de données MongoDB
  # Il sert aussi bien en développement qu'en production locale
  mongo:
    
    image: mongo:8
    container_name: flemot-mongo-db
    
    ports:
      - "27017:27017"
    # Volume pour garder les données persistantes, même après redémarrage
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

volumes:
  # Volume Docker pour stocker les données MongoDB
  mongo-data:
