# Version du fichier Docker Compose
version: '3.8'

services:
  api:
    # Nom du conteneur pour l’API en production
    container_name: flemot-api

    # Construction de l’image à partir du dossier backend, même Dockerfile que pour dev
    build:
      context: ./backend

    ports:
      - "8000:8080"

    # Démarrage après que MongoDB soit prêt
    depends_on:
      - mongo

    # Charger les variables d’environnement depuis .env
    env_file:
      - .env

    # --- Différences avec la version dev ---
    # Pas de volume pour synchroniser le code (code figé dans l’image)
    # Pas de "dotnet watch", on utilise la commande par défaut du Dockerfile
    # Redémarrage automatique en cas de plantage (utile en production)
    restart: always
