name: .NET backend CI

on:
  push:
    branches: [ "main" , "develop" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup .NET
                - name: Setup .NET
                uses: actions/setup-dotnet@v4
                with:
                  dotnet-version: 9.0.x 
                  
      - name: Build project
        run: dotnet build ./backend --configuration Release